"""HS-13 포지션 브리프·서치 패킷 패키지의 공개 경계."""

from .boolean_query import BooleanQuerySet, build_boolean_queries, check_balanced
from .jd_fidelity import (
    EXTRA_CONDITION_PATTERNS,
    FidelityReport,
    Section,
    content_lines,
    extract_block,
    normalize_line,
    split_sections,
    verify_fidelity,
)
from .packet import PacketStore, from_json, packet_id, to_json
from .send_ledger import (
    Approval,
    SendIntent,
    SendState,
    Transition,
    load_attempt,
    load_intent,
    mark,
    may_send,
    open_new_attempt,
    record_intent,
)
from .types import (
    BriefInputError,
    Claim,
    CompanyBrief,
    ExecProfile,
    JdSource,
    PositionSpec,
    SourceRef,
)
from .types_candidate import (
    CandidateEvidence,
    CandidateLead,
    ConnectionDegree,
    EmailContact,
    ScoreBreakdown,
)
from .types_packet import JdPacket, SearchPacket, TeamMail

__all__ = [
    "EXTRA_CONDITION_PATTERNS",
    "Approval",
    "BooleanQuerySet",
    "BriefInputError",
    "CandidateEvidence",
    "CandidateLead",
    "Claim",
    "CompanyBrief",
    "ConnectionDegree",
    "EmailContact",
    "ExecProfile",
    "FidelityReport",
    "JdPacket",
    "JdSource",
    "PacketStore",
    "PositionSpec",
    "ScoreBreakdown",
    "SearchPacket",
    "Section",
    "SendIntent",
    "SendState",
    "SourceRef",
    "TeamMail",
    "Transition",
    "build_boolean_queries",
    "check_balanced",
    "content_lines",
    "extract_block",
    "from_json",
    "load_attempt",
    "load_intent",
    "mark",
    "may_send",
    "normalize_line",
    "open_new_attempt",
    "packet_id",
    "record_intent",
    "split_sections",
    "to_json",
    "verify_fidelity",
]
